config/routes.rb
SampleApp::Application.routes.draw do

  devise_for :admins
  
  get '/' => 'dashboard#index'

  resources :race_details

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :race_details
end

app/models/race_detail.rb
class RaceDetail < ActiveRecord::Base
  attr_accessible :event_city, :event_date, :event_name, :event_state,:admin_id,:race_type
  belongs_to :admin
  serialize :race_type, Hash
  validates :event_name,:event_city,:event_state,:event_date, presence: true
  validates :event_name, uniqueness: { case_sensitive: false }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
 def index

 end
end

app/controllers/race_details_controller.rb
class RaceDetailsController < ApplicationController
	before_filter :authenticate_admin!
	
	
	def new
		@race_detail = RaceDetail.new
	end

	def create
		race_detail = RaceDetail.new(params[:race_detail])
		if race_detail.save!
			flash[:success] = "Race detail created successfully."
		else
			flash[:error] = "Race Detail can not be created." 
		end

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/race_details_helper.rb
module RaceDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%if current_admin %>
		<div class="navbar navbar-fixed-top navbar-inverse">
			<div class= "navbar-inner">
		        <div class="container">
		           <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					</a>
					<ul class="nav pull-right">
					  <li class="dropdown">
					    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0);">
					      <%= current_admin.email %>
					      <b class="caret"></b>
					    </a>
					    <ul class="dropdown-menu">
					      <li>
					        <%= link_to "Update Profile", "#", method: :get %>
					      </li>
					      <li>
					        <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
					      </li>
					    </ul>
					  </li>
					</ul>
	        	</div>
	    	</div>
		</div>
	<%else%>
		<div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="#">Logo</a>
                <ul class="nav">
                    <li><a href="#">Marathon Calender</a></li>
                    <li><a href="#">Upcoming Marathon</a></li>
                    <li><a href="#">News</a></li>
                    <li><a href="#">Running Club</a></li>
                    <li><a href="#">Blog</a></li>
                </ul>
                <div class="pull-right">
                    <%= link_to "Admin Login",race_details_path %>

                </div>
            </div>
        </div>
    </div>


	<% end%>

	<div class= "container">
		<div class="starter-template">
	        <%= bootstrap_flash%>
			<%= yield %>
		</div>
      </div>
	</div>

</body>
</html>

app/views/race_details/index.html.erb
<div class = "mainContainer">
	
	<h3> Welcome to Running Life App </h3>
	<%= link_to "Create Event",new_race_detail_path,class:"btn btn-primary pull-right" %>
	
</div>

app/views/race_details/new.html.erb
<%= form_for :race_detail,url: race_details_path(@race_detail),html: { class: "well form-horizontal"} do |f|%>
	<legend style='align: center;'>Create Race Event</legend>
	<%=f.hidden_field :admin_id, value:current_admin.id %>
	<div class="control-group">
	    <%= f.label :event_name, class: "control-label" %>
	    <div class="controls">
	      <%= f.text_field :event_name %>
	    </div>
	  </div>
	  <div class="control-group">
	    <%= f.label :event_date, class: "control-label" %>
	    <div class="controls">
	      <%= f.text_field :event_date %>
	    </div>
	  </div>
	  <div class="control-group">
	    <%= f.label :event_state, class: "control-label" %>
	    <div class="controls">
	      <%= f.text_field :event_state %>
	    </div>
	  </div>
	  <div class="control-group">
	    <%= f.label :event_city, class: "control-label" %>
	    <div class="controls">
	      <%= f.text_field :event_city %>
	    </div>
	  </div>
	  <div class="control-group">
	    <%= f.label :event_date, class: "control-label" %>
	    <div class="controls">
	      <%= f.text_field :event_date %>
	    </div>
	  </div>
	 
	  <div class="checkbox">
  		<%= f.fields_for :race_type do |n| %>
	  		<label>
	    		<%= n.check_box :half_marathon, checked: true , class: "control-label"%>
	  		</label>
	  	<%end%>
	  </div>
    
   

	  <div class="control-group">
	    <div class="controls">
	    <button type="submit" class="btn btn btn-success formSubmit pull-left">Submit</button>
	    <%=link_to "back", race_details_path, class:"btn btn-default pull-right"%>
	    </div>
	  </div>
<%end%>